### ISSUE TITLE
Display player KD, fix item update [suggestion][bug]

### ISSUE THREAD

**Issue by OneB1ank** [HuiTeab/EFT-DMA-Radar-v2#4]
Suggest displaying the player's KD and survival rate, so we can know if their data is normal. When an item is picked up, it still appears on the radar, requiring a radar restart to update.

**Comment by HuiTeab** [comment]
Thank you for your feedback and suggestions. I understand your interest in seeing other players' KD (Kill/Death ratio) and survival rate data to evaluate normal gameplay patterns. However, I want to clarify that accessing other players' KD and survival data directly from the game data. While it is technically feasible to extract some data through the Tarkov API, the details are encrypted. Due to this encryption, I have not attempted to retrieve that specific information. 
As for the radar issue you've mentioned, I'd like to clarify that this behavior is currently by design, Each map in the game contains approximately 500 loot objects(lootable items and streets is x4), and trying to update these objects in real-time on the radar could potentially introduce other issues due to the high volume of data being processed. Future plan most likely involves displaying loot only within a certain distance from the player, which should make it more manageable to update this information live.
